export const ADMIN_ROUTE = '/admin'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const DEVICE_ROUTE = '/device'
export const BASKET_ROUTE = '/basket'
export const FAVORITE_ROUTE = '/favorites'
export const ORDER_ROUTE = '/orders'